# Generated by Django 4.1.4 on 2022-12-28 22:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_coreuser_age_remove_coreuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.dish_upload_path),
        ),
    ]
